# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk"

rule all:
    input:
        #expand("results/concatenated/{sample}.{paired}.fq.gz", sample=samples['sample'], paired=['R1','R2'])
        #expand("results/rcorrector/{sample}", sample=samples['sample'])
        #"results/assembly_trinity"
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        #"results/busco_transcriptome/trinity_busco",
        #"results/full-length_transcript/blastx.outfmt6.group",
        #"results/full-length_transcript/blastx.outfmt6",
        #"results/full-length_transcript/blastx.outfmt6.txt.w_pct_hit_length",
        "results/quantification/kallisto.isoform.counts.matrix",
        #expand("results/representatation_assembly/{sample}_align_stats.txt", sample=samples['sample'])


include: "rules/common.smk"
include: "rules/quality_control.smk"
include: "rules/assembly.smk"
include: "rules/assembly_quality.smk"
